### ISSUE TITLE
Crash on console when logging in with wrong pasword

### ISSUE THREAD

**Issue by tuvokki** [tuvokki/Huna_Server#43]
```
TypeError: Cannot read property '0' of null
    at http://localhost:4000/js/vendor/vendor.js:199:317
    at f (http://localhost:4000/js/vendor/vendor.js:216:74)
    at n.$eval (http://localhost:4000/js/vendor/vendor.js:126:15)
    at n.$apply (http://localhost:4000/js/vendor/vendor.js:126:241)
    at HTMLFormElement.<anonymous> (http://localhost:4000/js/vendor/vendor.js:216:126)
    at HTMLFormElement.c (http://localhost:4000/js/vendor/vendor.js:32:389) undefined undefined undefined undefinedwindow.onerror @ huna.min.js:24console.error @ huna.min.js:17(anonymous function) @ angular-resource.js:6(anonymous function) @ angular-resource.js:6n.$apply @ angular-resource.js:6(anonymous function) @ angular-resource.js:6c @ angular-resource.js:6
huna.min.js:18 TypeError: Cannot read property '0' of null
    at angular-resource.js:6
    at f (angular-resource.js:6)
    at n.$eval (angular-resource.js:6)
    at n.$apply (angular-resource.js:6)
    at HTMLFormElement.<anonymous> (angular-resource.js:6)
    at HTMLFormElement.c (angular-resource.js:6)console.error @ huna.min.js:18(anonymous function) @ angular-resource.js:6(anonymous function) @ angular-resource.js:6n.$apply @ angular-resource.js:6(anonymous function) @ angular-resource.js:6c @ angular-resource.js:6
huna.min.js:73 XHR succeeded 200
```

**Comment by tuvokki** [comment]
Occurs in:
huna.min.js (line 24)

```
  window.onerror = function(err, script, line, col, cause){
    console.oldError(err, script, line, col, cause);
    // harvest as much information as we need...
```

huna.min.js (line 18)

```
    window.onerror(err);
    console.oldError(err);
  };
```

**Comment by tuvokki** [comment]
Only happens after long browser timeout. After refreshing:

```
    Navigated to http://localhost:4000/
    huna.min.js:14 Initializing HunaJS
    angular-resource.js:6 POST http://localhost:4000/api/login 422 (Unprocessable Entity)b @ angular-resource.js:6n @ angular-resource.js:6$get.f @ angular-resource.js:6(anonymous function) @ angular-resource.js:6$get.n.$eval @ angular-resource.js:6$get.n.$digest @ angular-resource.js:6$get.n.$apply @ angular-resource.js:6(anonymous function) @ angular-resource.js:6c @ angular-resource.js:6
    app.js:558 data, status, headers, config Object {error: "Error signing in"} 422 anonymous(c) Object {method: "POST", transformResponse: Array[1], url: "/api/login", data: Object, headers: Object}
```
